apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: cert-sync
    app.kubernetes.io/managed-by: kustomize
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUND_ID>:role/eks-acm-controller
  name: controller-manager
  namespace: system
